[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
hall_of_fame = "7NbDu94EJ5kQhq8qnBoNKKGRzDoQDzxRf9eBQjjPWtK1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
